
apiVersion: v1
kind: Secret
metadata:
  name: seera-pos-secrets
type: Opaque
data:
  # Replace YOUR_BASE64_ENCODED_AI_KEY with your actual AI_PROVIDER_API_KEY, base64 encoded.
  # To encode: echo -n "your_actual_ai_key" | base64
  AI_PROVIDER_API_KEY: YOUR_BASE64_ENCODED_AI_KEY_HERE

  # Replace YOUR_BASE64_ENCODED_GOOGLE_CREDS with your Google Service Account JSON content, base64 encoded.
  # To encode (ensure the JSON is a single line or handle newlines carefully before encoding):
  # cat /path/to/your/service-account-file.json | base64 -w 0
  # Ensure the JSON content itself does not contain unescaped newlines before encoding.
  # It's often easier to minify the JSON to a single line first.
  GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: YOUR_BASE64_ENCODED_GOOGLE_CREDS_HERE
