
apiVersion: v1
kind: Secret
metadata:
  name: seera-pos-secrets
type: Opaque
data:
  # AI_PROVIDER_API_KEY is no longer strictly required here by the deployment.
  # If you have one and want to store it, you can still base64 encode it and add it:
  # AI_PROVIDER_API_KEY: YOUR_BASE64_ENCODED_AI_KEY_HERE

  # GOOGLE_SERVICE_ACCOUNT_CREDENTIALS is still required.
  # Replace YOUR_BASE64_ENCODED_GOOGLE_CREDS with your Google Service Account JSON content, base64 encoded.
  # To encode (ensure the JSON is a single line or handle newlines carefully before encoding):
  # cat /path/to/your/service-account-file.json | jq -c . | base64 -w 0
  # Ensure the JSON content itself does not contain unescaped newlines before encoding.
  GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: YOUR_BASE64_ENCODED_GOOGLE_CREDS_HERE
