
apiVersion: v1
kind: Service
metadata:
  name: seera-pos-service
spec:
  type: NodePort # Use NodePort for easy access on Minikube
  selector:
    app: seera-pos # This must match the labels in your Deployment's template
  ports:
  - protocol: TCP
    port: 80 # Port the service will be available on *within* the Minikube cluster
    targetPort: 3000 # Port your application container is listening on
    # nodePort: 30007 # Optional: specify a NodePort, or let Kubernetes assign one
